"""change table name to resorts

Revision ID: 467416e5a7e9
Revises: ac4ba42082c0
Create Date: 2022-09-02 18:36:38.304539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467416e5a7e9'
down_revision = 'ac4ba42082c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
