"""added resorts

Revision ID: 6edc0afab359
Revises: f0b85a5d90b0
Create Date: 2022-09-04 16:56:14.062495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6edc0afab359'
down_revision = 'f0b85a5d90b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
