"""first revision

Revision ID: 33e14bdc9c8a
Revises: f200ef36f6b1
Create Date: 2022-09-02 19:37:28.485404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e14bdc9c8a'
down_revision = 'f200ef36f6b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
