"""add resort

Revision ID: ad7efbfa8423
Revises: 6edc0afab359
Create Date: 2022-09-04 19:16:01.885748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad7efbfa8423'
down_revision = '6edc0afab359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
